export const themes = [
  {
    id: "knowing",
    index: "01",
    eyebrow: "ORIGIN / 起源",
    title: "关于「知」与「行」",
    statement: "听过不等于懂，做到才是真的知道。",
    range: [1, 11],
    accent: "#d6ff36",
  },
  {
    id: "benefits",
    index: "02",
    eyebrow: "PROOF / 印证",
    title: "知行合一的好处",
    statement: "错了，知道错在哪。对了，知道如何再来一次。",
    range: [12, 19],
    accent: "#f3ffbd",
  },
  {
    id: "coherence",
    index: "03",
    eyebrow: "COHERENCE / 自洽",
    title: "关于自洽",
    statement: "各走各的路，都不内耗。",
    range: [20, 26],
    accent: "#b8b5ff",
  },
  {
    id: "action",
    index: "04",
    eyebrow: "ACTION / 行动",
    title: "关于行动",
    statement: "用行动说话，用作品说话。",
    range: [27, 35],
    accent: "#ff784f",
  },
  {
    id: "honesty",
    index: "05",
    eyebrow: "HONESTY / 诚实",
    title: "诚实与自我认知",
    statement: "颗粒度里，全是你还不知道的东西。",
    range: [36, 45],
    accent: "#d6ff36",
  },
  {
    id: "errors",
    index: "06",
    eyebrow: "REVISION / 修正",
    title: "错误与希望",
    statement: "改认知，出行为，拿结果。",
    range: [46, 53],
    accent: "#7bdcff",
  },
  {
    id: "desire",
    index: "07",
    eyebrow: "DESIRE / 欲望",
    title: "欲望与幸福",
    statement: "求仁得仁，才是真满足。",
    range: [54, 61],
    accent: "#ffd36a",
  },
  {
    id: "feedback",
    index: "08",
    eyebrow: "INNER / 内心",
    title: "内心与反馈",
    statement: "看见自己，然后边走边修正。",
    range: [62, 68],
    accent: "#f3ffbd",
  },
  {
    id: "attention",
    index: "09",
    eyebrow: "FOCUS / 定力",
    title: "注意力与独处",
    statement: "注意力放在哪里，必须由我说了算。",
    range: [69, 77],
    accent: "#b8b5ff",
  },
  {
    id: "relationships",
    index: "10",
    eyebrow: "RELATION / 关系",
    title: "识人与关系",
    statement: "跟正直的人同行，找互补的人同行。",
    range: [78, 87],
    accent: "#ff784f",
  },
  {
    id: "promise",
    index: "11",
    eyebrow: "PROMISE / 承诺",
    title: "承诺与说话",
    statement: "说话有代价，所以才有分量。",
    range: [88, 94],
    accent: "#d6ff36",
  },
  {
    id: "separation",
    index: "12",
    eyebrow: "FREEDOM / 分离",
    title: "关于课题分离",
    statement: "各人有各人的课题，各人也有各人的希望。",
    range: [95, 100],
    accent: "#7bdcff",
  },
];

const entries = [
  ["knowing", "听过不等于懂，做不到就是不知道。"],
  ["knowing", "知识五层：听过、了解、知道、掌握、精通。"],
  ["knowing", "听二十遍，也只是听过。"],
  ["knowing", "能讲清楚，只是了解；拿到结果，才叫知道。"],
  ["knowing", "能点破别人、复制经验，才叫掌握。"],
  ["knowing", "不要轻易说“我知道”，这是对知识的诚实。"],
  ["knowing", "没有执行的认知，是空中楼阁。"],
  ["knowing", "认知很强却赚不到钱？那就是没有认知。"],
  ["knowing", "真认知，既能落到最细的颗粒度，也能搭起底层框架。"],
  ["knowing", "道理要一层层落地：价值观、原则、模型、数据、事件，层层皆有印证。"],
  ["knowing", "落不到事上的道理，你并不真的懂。"],
  ["benefits", "知行合一最大的好处：错了，知道错在哪。"],
  ["benefits", "完全照着相信的去做，错了就改理论，不内耗。"],
  ["benefits", "想一套、说一套、做一套，你连错在哪都找不到。"],
  ["benefits", "知行混乱的人，人格都不稳定。"],
  ["benefits", "人生不好，倒推三步：坏习惯 ← 坏行为 ← 坏认知。"],
  ["benefits", "换思维，坚定执行，就会变好。所以你永远有希望。"],
  ["benefits", "学了很多道理却不做，才会绝望。"],
  ["benefits", "你不是做到了极限，你是根本没做。"],
  ["coherence", "知行合一的第二个好处：自洽。"],
  ["coherence", "雷军拼命是幸福，张云帆躺平也是幸福。各走各的路，都不内耗。"],
  ["coherence", "人生最大的痛苦：得非所愿，愿非所得。"],
  ["coherence", "得到的不是想要的，想要的总得不到，人就在空虚和焦虑之间摆。"],
  ["coherence", "把“应该要的”当成“想要的”，是大多数人痛苦的开始。"],
  ["coherence", "放弃思考的人，会被身份吃掉自我。"],
  ["coherence", "走在自己认为正确的路上，再累也不悔。"],
  ["action", "嘴上说好，身体不动，不叫知行合一。"],
  ["action", "想了不做，就是分裂；要么别想，要么就做。"],
  ["action", "显而易见的事你做不到，说明你脑子里根本不这么想。"],
  ["action", "先做，上车再说；别先问“我是谁”。"],
  ["action", "小的看不上，中的嫌累，大的做不了。最后只剩空想。"],
  ["action", "出来混，最重要的是先出来。"],
  ["action", "说到做到，无论多难多苦。"],
  ["action", "我对自己说什么，我就实现什么。这就是效能感。"],
  ["action", "用行动说话，用作品说话。"],
  ["honesty", "你说你知道了，为什么没做到？这就是不诚实。"],
  ["honesty", "你觉得那只股票会涨，为什么没买？先回答这个，再谈认知。"],
  ["honesty", "对自己最大的误会，是误以为知道的就能做到。"],
  ["honesty", "看着简单的事，做起来就四不像。颗粒度里全是你不知道的东西。"],
  ["honesty", "不要先行判断，先做。"],
  ["honesty", "半壶水才响叮当，真懂的人在拿结果。"],
  ["honesty", "嘴上的道理是提醒，不是践行。"],
  ["honesty", "我不信只讲复利却没活成复利的人。"],
  ["honesty", "芒格讲复利，他的人生本身就是复利。"],
  ["honesty", "说得多响亮都不重要，战绩才重要。"],
  ["errors", "风口不会错，错的是你没有坚定执行。"],
  ["errors", "三天打鱼两天晒网，你永远验证不了任何道理。"],
  ["errors", "所有事都只付一点点努力，等于什么都没验证。"],
  ["errors", "我做不到，是因为我不知道；那我就去知道。"],
  ["errors", "归因要精准：改认知，出行为，拿结果。"],
  ["errors", "后悔没买，是假后悔。你买了也拿不住。"],
  ["errors", "根本没听进去、没做过的事，不值得你后悔。"],
  ["errors", "它本来就跟你没关系，是你的认知还没到。"],
  ["desire", "求仁得仁，才是真满足。"],
  ["desire", "你追求的就是你要的，这叫自洽。"],
  ["desire", "马斯克不缺钱，他缺的是改变世界；不让他干，浑身痒。"],
  ["desire", "闲云野鹤的人硬当 CEO，是自我折磨。"],
  ["desire", "选了皇位，就要干皇帝的事；不想干，就别要那个位置。"],
  ["desire", "为钱而活、为别人的眼光而活，就是走上了自己不想走的路。"],
  ["desire", "每个人快乐的开关不一样，别用别人的开关点自己的灯。"],
  ["desire", "赚到钱不难，赚到钱还活得通透，才难。"],
  ["feedback", "刚韧的内心，来自漫长时间里爱的滋养。"],
  ["feedback", "先有正反馈打底，才扛得住负反馈。"],
  ["feedback", "承认自己有欲望、有虚荣心，接受它，再慢慢修。"],
  ["feedback", "把自己重新养一遍，就是在最匮乏的地方补上好的反馈。"],
  ["feedback", "你看见别人，才能看见自己。"],
  ["feedback", "得非所愿可以是过程，但不能是终点。"],
  ["feedback", "知道自己正走偏，就要边走边修正。"],
  ["attention", "保护好你的注意力，它是你最贵的资产。"],
  ["attention", "定时看群，不要随时被打扰。"],
  ["attention", "高频信息流不是学习，是另一种刷短视频。"],
  ["attention", "能独处，才能听见自己的情绪。"],
  ["attention", "安住当下，心流会替你屏蔽噪音。"],
  ["attention", "对过去复盘，对现在专注。"],
  ["attention", "有钱人想安静看半小时书都难。那不是我要的生活。"],
  ["attention", "真正的自由，是有能力拒绝你不要的生活。"],
  ["attention", "我的注意力放在哪，必须由我说了算。"],
  ["relationships", "远离 drama 的人，远离烂人。"],
  ["relationships", "跟正直的人合作，不成也不会被害。"],
  ["relationships", "战绩一直为负的人，一定有原因。"],
  ["relationships", "不想认识一辈子的人，一秒钟都别多待。"],
  ["relationships", "远离烂人的想法，也远离他身边的关系。"],
  ["relationships", "黑暗的价值观：不听、不看、不想、不进脑子。"],
  ["relationships", "合作不等于认同，兄弟也分远近。"],
  ["relationships", "标签有道理，但标签就是用来打破的。"],
  ["relationships", "找互补的人，补你最缺的那块。"],
  ["relationships", "感性的人，要去补理性的朋友。"],
  ["promise", "说话要有时间、有日期，不能无限拖。"],
  ["promise", "承诺太多，就意味着坑没填。"],
  ["promise", "话只说够得着的，不乱许诺。"],
  ["promise", "答应了的事，熬着也要做完。"],
  ["promise", "说话有代价，所以才有分量。"],
  ["promise", "我说的事必然实现。这是我对自己的预言。"],
  ["promise", "先要求自己说话算数，才有资格要求别人。"],
  ["separation", "不要替别人难过，各人有各人的课题。"],
  ["separation", "孩子吃苦，也是孩子自己的课题。"],
  ["separation", "讨厌你的人攻击不到你，除非你一直想着他在想什么。"],
  ["separation", "他占不掉你的心智，是你自己交出去的。"],
  ["separation", "接受讨厌的人只是过程，你终会去到喜欢的人身边。"],
  ["separation", "到了那个时候，自然会有那个时候的希望，所以不用怕。"],
];

export const quotes = entries.map(([theme, text], index) => ({
  number: index + 1,
  theme,
  text,
}));

export function quotesForTheme(themeId) {
  return quotes.filter((quote) => quote.theme === themeId);
}

